### ISSUE TITLE
[FEATURE] Add primary/secondary category to 3rd party listing

### ISSUE THREAD

**Issue by sreichel** [m2epro/magento-extension#4]
HI,

we've spent couples of our to assign categories for thousands of items we have moved from 3rd party to M2E listings ... ;)

As far as i can see in eBay's API refererences, most call (like `GetSellerList`, `GetItem`, `GetMultipleItems`) also return category IDs.

Would be nice to store these data to 3rd party listings and keep them assigned, when moving items to M2E listings.

**Comment by m2epro** [comment]
3rd party solution will have significant changes in the nearest future, so this doesn't have sense at the moment.
