### ISSUE TITLE
Company data missing when creating user

### ISSUE THREAD

**Issue by sreichel** [m2epro/magento-extension#5]
Hi,

i appriciate it see M2E on Github ... :) Thinks it's the better way to report issues than writing mails to you 1st level support ;)

This one was already reported to your support team and confirmed as a bug!

When M2E creates orders in Magento, order billing/shipping adress contain all data, but for the created user account company data is missing.

**Comment by m2epro** [comment]
please raise the ticket by email. our support mailbox is support@m2epro.com. we don't provide issue tracking through the github.
