### ISSUE TITLE
No support for custom price attributes

### ISSUE THREAD

**Issue by sreichel** [m2epro/magento-extension#6]
M2E only offers curreny rates for `price` and `special_price` attribute, but Magento offers the ability to add custom attributes with type price ... for these attributes it is not possible to apply currency rates.

In our scenario - we sell int'l - and ebay prices differ from store price, it's not possible to just use
- `price_ebay`
- `price_ebay_best_offer`

... cause curreny rates are not applied. We had to create price attributes for every single currency, like ...
- `price_ebay` (EUR)
- `price_ebay_best_offer`
- `price_gbp_ebay`
- `price_gbp_ebay_best_offer`
- `price_usd_ebay`
- `price_usd_ebay_best_offer`
- `price_cad_ebay`
- `price_cad_ebay_best_offer`
- ...

... and apply currency rates via script.

Downside .... with every product save, Magento runs `applyPriceRules` for every price attribute, eating up a lot of resources ... especially when price scope isset to website (multistore enviroment with different prices).

... `products` * `websites` * `pricefields` ...

This should be fixed ASAP for ALL int'l sellers!

**Comment by m2epro** [comment]
m2epro uses github at this moment only as a way to provide alternative method for upgrading extension for our customers. any pull requests or bugs should be mailed to support@m2epro.com
